spring.application.name=sgri

# CONNECTION CONFIGURATION
spring.datasource.url=jdbc:mysql://db:3306/db_gestion_recursos?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=78800880
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# FLYWAY CONFIGURATION
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false
spring.flyway.clean-disabled=false


# JPA HIBERNATE CONFIGURATION
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true