services:
  # 1. Contenedor de la Base de Datos (MySQL)
  db:
    image: mysql:8.0
    container_name: mysql_backend
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 78800880
      MYSQL_DATABASE: db_gestion_recursos
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # 2. Contenedor Backend (Java Spring Boot con Java 21)
  backend:
    image: maven:3.9-eclipse-temurin-21
    container_name: spring_backend
    restart: always
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - ./spring-app:/app
      - maven_cache:/root/.m2
    depends_on:
      - db
    command: mvn spring-boot:run

volumes:
  mysql_data:
  maven_cache: